version: '3.8'
services:
  qdrant:
    build:
      context: ./qdrant
    image: qdrant_local
    ports:
      - '6333:6333'
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    environment:
      - QDRANT_URL=http://qdrant:6333
    ports:
      - '8000:8000'
    depends_on:
      - qdrant
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend